### ISSUE TITLE
plan for the next version

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/datasets#13]
- [x] remove DataType
- [x] rename Location to Resource or smth
- [x] add String-type resource
- [x] remove file-types

**Comment by eparejatobes** [comment]
The next version will be based on cosas `0.8`, which brings a lot of simplifications. This is a quick summary of how I think we should approach changes here

1. Datasets will/should become redundant. Either `ProductType`s or `Record`s should be enough.
2. Locations can be just `AnyLocation`, with `AnyFileLocation` and `AnyS3Location` as subtypes. If you need (like in *loquat*) to restrict to a denotation composed of files, use `Ds <: DS := KList.Of[AnyFileLocation]`.

That should be all I think. It would be good to add depfns for some common uses.

**Comment by eparejatobes** [comment]
I could reduce this to essentially just `AnyData` and `Location` with a small modification on product types (making them generic on a bound <: AnyType).

**Comment by eparejatobes** [comment]
@laughedelic take a look

**Comment by laughedelic** [comment]
@eparejatobes do I understand right that 
```scala
type AnyLocation = AnyDenotation { type Tpe <: AnyData }

type FileLocation = AnyLocation { type Value = File }
type S3Location = AnyLocation { type Value = S3Address }
```
? i.e. no separate types for these things

**Comment by eparejatobes** [comment]
hola!

**Comment by eparejatobes** [comment]
- [ ] remove DataType
- [ ] rename Location to Resource or smth
- [ ] add String-type resource
- [ ] remove file-types

**Comment by laughedelic** [comment]
Done :ok_hand: 
Now I'm going to implement https://github.com/ohnosequences/loquat/issues/28 and if nothing is needed from datasets, we can release it.

**Comment by eparejatobes** [comment]
@laughedelic everything fine in Loquat right? if so let's release this

**Comment by laughedelic** [comment]
ok

**Comment by laughedelic** [comment]
Done: [v0.3.0](https://github.com/ohnosequences/datasets/releases/tag/v0.3.0) :shipit:
