### ISSUE TITLE
add common file extensions

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/datasets#22]
this is just a matter of copy-pasting from a list.
- https://en.wikipedia.org/wiki/List_of_filename_extensions_%28alphabetical%29
- http://fileinfo.com/filetypes/common
- http://genome.ucsc.edu/FAQ/FAQformat.html

It would be nice to differentiate (and link) file formats and file extensions.

**Comment by laughedelic** [comment]
In #13 we have decided to remove filetypes for now.
